#include "..\include\Problem2.h"
#include <iostream>

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
*  By starting with 1 and 2, the first 10 terms will be:
*  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*
*  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
*  find the sum of the even-valued terms.
*/

Problem2::Problem2() {

}

void Problem2::runProblem2(int limit, bool debugInfo){

    int first   = 0;
    int second  = 1;
    int temp    = 0;
    int sum     = 0;

    //While term is less than limit, new term is sum of old terms.
    while((temp = first + second) < limit){
        // Print info if requested
		if (debugInfo) {
			std::cout << "Term " << temp;
		}

        //Check if term is even.
        if (!(temp % 2)){
            sum += temp;
			if (debugInfo) {
				std::cout << " is even." << std::endl;
			}
        }else{
			if (debugInfo) {
				std::cout << " is odd." << std::endl;
			}
        }

        //Update terms
        first   = second;
        second  = temp;
        temp    = 0;
    }

    //Write the sum.
    std::cout << "The sum of the even fibonacci numbers is " << sum << std::endl;
}
